### PR TITLE
Add package and struct name to OperationInfo

### PR DESCRIPTION
**Pull request by armandpicard**
Signed-off-by: Armand Picard <a.picard@instadeep.com>

### CODE REVIEW

**Comment by wI2L** [comment]
Fixes #61

**Comment by wI2L** [comment]
I'll be willing to merge that if it doesn't change the current behaviour. So it must be an opt-in option on the generator.

**Comment by armandpicard** [comment]
I've put a function in the generator that is use to generate the name from the handler.
It's set to `(*tonic.Route).HandlerName` and can be change by the user.

**Comment by wI2L** [comment]
@armandpicard Still willing to merge, apologies for the delay. Could you add some tests and a mention of the function method in the README please.

**Pull request closed without merging**
